### ISSUE TITLE
got error after run test.py

### ISSUE THREAD

**Issue by wisan-dhammatorn** [Championchess/A-Tri-Layer-Plugin-to-Improve-Occluded-Detection#4]
I got error message when I tried to run "python tools/test.py mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco_our_plugin.py "" --eval bbox segm"

I copied all code in "config" you provided link in Model table and save as .py 
CONFIG_FILE' name is  "mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco_our_plugin.py"

How can I solve this problem? 

Error message:
apex is not installed
apex is not installed
apex is not installed
apex is not installed
loading annotations into memory...
Done (t=0.28s)
creating index...
index created!
/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
load checkpoint from local path: 
Traceback (most recent call last):
  File "tools/test.py", line 239, in <module>
    main(ckpt_pth, real_ann_json, real_img_folder, real_result_save_pth, real_max_iter)
  File "tools/test.py", line 184, in main
    checkpoint = load_checkpoint(model, ckpt_pth, map_location='cpu')
  File "/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 531, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 470, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 249, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 265, in load_from_local
    raise IOError(f'{filename} is not a checkpoint file')
OSError:  is not a checkpoint file

**Comment by Championchess** [comment]
Hello, you need to fill in "path to coco val annotations", "path to coco val images", "path to save detection results", "path to checkpoint" in test.py before you run it, as mentioned in the github instructions.

**Comment by wisan-dhammatorn** [comment]
Thank you very much. I have filled all paths in test.py as you suggested but I still got error message when I tried to run test.py. 

How can I solve that problem. Thank you in advance.

apex is not installed
apex is not installed
apex is not installed
apex is not installed
loading annotations into memory...
Done (t=0.26s)
creating index...
index created!
/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
load checkpoint from local path: mmcv/runner/checkpoint.py
Traceback (most recent call last):
  File "tools/test.py", line 239, in <module>
    main(ckpt_pth, real_ann_json, real_img_folder, real_result_save_pth, real_max_iter)
  File "tools/test.py", line 184, in main
    checkpoint = load_checkpoint(model, ckpt_pth, map_location='cpu')
  File "/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 531, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 470, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 249, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 266, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/arm/anaconda3/envs/occ/lib/python3.7/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '#'.

**Comment by Championchess** [comment]
Hi, you need to download the pre-trained models on our github page and fill in "path to checkpoint".
